---
title: "BrainMaps: Correlation Matrix and Spin Tests"
author: "Valerie Jill Sydnor"
output: 
  html_document:
    theme: flatly
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(matrixStats)
library(ggcorrplot)
```
\ 
\ 

```{r echo=TRUE}
brains <- read.csv("./brainmaps_glasser.csv", header=TRUE) #read in cortical map data
brains <- brains[ , order(names(brains))] #order columns alphabetically in reference df
brains.matrix <-  as.matrix(brains[ , order(names(brains))]) #order columns alphabetically in matrix

spherical.coordinates <- read.table("./glasser_spherical_coordinates.txt", header=F) #glasser parcel spherical coordinates (FreeSurfer sphere) for the 180 left hemisphere parcels. Coordinates taken (first 180 rows) from the sphere_HCP.txt file provided here https://github.com/frantisekvasa/rotate_parcellation
spherical.coordinates <- as.matrix(spherical.coordinates) #format as matrix
```
\ 
\ 
*Source Parcel-Based Spherical Spatial Permutation Test (Spin Test) Functions*
```{r echo=TRUE}
# Parcel-based spatial permutation test (spin test) functions
### Functions were originally obtained from https://github.com/frantisekvasa/rotate_parcellation/tree/master/R 
### rotate.parcellation.R was modified to only spatially rotate left hemisphere coordinates on the sphere
### Parcel-based tests implemented as described in Váša et al. (2018) doi:10.1093/cercor/bhx249 , based on original work from Alexander-Bloch et al. (2013) doi:10.1523/JNEUROSCI.3554-12.2013 and Alexander-Bloch et al. (2018) doi:10.1016/j.neuroimage.2018.05.070
source("./rotate_parcellation/R/rotate.parcellation.R") #modified to accept only coord.l and nrot as arguments
source("./rotate_parcellation/R/perm.sphere.p.R")
```
\ 
\ 
*Compute Spearman's Rank Correlation Matrix and Pspin Matrix*
```{r eval=FALSE, echo=TRUE}
correlation.matrix = permutedp.matrix = array(NA, dim=c(10,10)) #create empty matrices 

for(i in 1:10){
  for(j in 1:10){
    perm.id <- rotate.parcellation(spherical.coordinates, nrot=1000) #1000 spherical rotations
    correlation.matrix[i,j] = cor(brains.matrix[,i], brains.matrix[,j], method = c("spearman")) #spearman's rank correlation matrix
    permutedp.matrix[i,j] = perm.sphere.p(brains.matrix[,i], brains.matrix[,j], perm.id) #spatial permutation based p-value matrix
  }
}

save(correlation.matrix, file="./spearmans.correlation.matrix.Rdata") #save correlation matrix
save(permutedp.matrix, file="./spintests.p.matrix.Rdata") #save permuted p-value matrix
```

```{r echo=TRUE}
load("./spearmans.correlation.matrix.Rdata") #load saved correlation matrix
load(file="./spintests.p.matrix.Rdata") #load saved p-value matrix
```
\ 
\ 
*Visualize Correlation Matrix*
```{r, echo=TRUE}
correlation.matrix <- as.data.frame(abs(correlation.matrix)) #format as df
colnames(correlation.matrix) <- colnames(brains)
rownames(correlation.matrix) <- colnames(brains)

correlation.matrix.reordered <- correlation.matrix[, c(3, 5, 8, 7, 2, 9, 1, 4, 6, 10)] #reorder mat columns
correlation.matrix.reordered <- correlation.matrix.reordered[c(3, 5, 8, 7, 2, 9, 1, 4, 6, 10),] #reorder mat rows

ggcorrplot(correlation.matrix.reordered, method = "square", type = "upper", show.legend = TRUE, show.diag = FALSE, lab = FALSE, hc.order = F, colors = c("#6f1282", "white", "#6f1282"), outline.color=c("white"))

ggsave(filename = "./visualizations/CorrelationMatrix.pdf", device = "pdf", dpi = 300, width = 6 , height = 6)
```

